# Config file for automatic testing at travis-ci.com

language: python
python:
- 3.9
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: "Xmhhyb2AuJZ7Jb2blUbB90/pqlVq0VSRlibkVhLQBvMkgnpoXECBMX//peHOAZqXjV2XXc6Fp2LQPRKbJgJGey23iq7CheMEhdqaFSc5i475wQ2r3L4O0OnbsLEbjtYFOB4eawDBh216mnfYLDWd0WCM9FcpGypCFmCp0miYv/fkOycV/9Ghow25/T2o/FiSTiY2BRZKJo/7ysjiu7m49d72hzass3pSi6sdvFNC5AaJXD+j5crqBjeQ8DaJMAs9KYa9fU5tPUF41hNgvohONu2jMS44rAWSHBJvj8rgxvIA9XVR43ooSVNioch0yM8+vIQSPF6Hpt3i6i0nIX2gK94a4bZbmwskdEOYRQf5pGsYLVN1507GkbXfdjrwdfnjICK7BH2+s2i5f0uMcl0WBSLveEg8qXfRXbL/NXupnttNtwQ+HHc6k5aYsu8mOo/zoKcQM1OUyHUGz61aIO+HDpRfNR03jBMcw9zCQ8f07/Fdj7T/z20Y9ePtbh57aaSUBxdskyWbm4RhSSndDpM6LnCkNwTWUCtXzQuuNI6k80rV6tiJMRKyddVZ/czJ3Gm3rfnXFyQWNB2ej77nfujn7cp2RU+xEKQ7JPB0ZzTDMBkF8zeTEEMOyAeFc6Wg+czHT29fvA6Ii1He2/JyGQW3K7VAkWwkx1PFjQ3l02FzHrc="
  true:
    tags: true
    repo: anascacais/epibox
    python: 3.9
env:
  global:
    secure: S/eBoTMqnihOxW61roFeNDZyUoaVd+j58+mLDpwAOgVcBcaFbbBW2d2LKmXBBhEHWtyyWzHkWGR8wvokYwn68bawvqdMwhiqvQLuVKYXL1GjxVuSuyIqMigvta7TXhbNG000ZqEv3XUNDK+cbNp2xnEqCXWLnuwe570NaPAC6W6BTXCXyil6T+sEYLhgFTeOsSxQuXNHM8UV16Fn28GZV6Ahg3b4Jk6GMnjMCBE21NEEd0eFzUOueHtqan3azCrsQDjmfGpQLKoCGEO9NVZBYGEqZxk7dcMq5naYuYx8srzD5afwYcN7aBVq59EhsvgHq0arPrLQV5U6+XM4AeeO9Si2ra6tSzyislmK/sbJkwuZjShqOSKCMOn5A5lGe8ZKM3phQg+X/gS0t6kX9qFx1yXoItwmvGJ3zXwbZNjQ7+lQwXF4wu5J0j+TCpZIO4wmrTYzZMx51XVHFjoKwbUel91vGcltm1nh4NBG1z35jxMMXB3Abgjf0gooHaXjKAgVkzX1SGN/8IBCdHjV/HfdGrxZzdf6EL9M4Xic+jVShiuOgXvPZ58Tj9T05pcXsn7/JFRzpbWnyz+NXqh1Kh4oOEeabfk0RXchg64EjeQr7OpIQcr72iw5494mMwsaXOcDzU4vQ7qmjwJ8qwwRYTW7GSkekvqqRqp0bsJwQT2ORKU=
